using ChallengeApp;
using System.Runtime.InteropServices;
var employee = new Employee("Michal", "Tomasiuk");
employee.AddGrade(1);
employee.AddGrade(5);
employee.AddGrade(8);
var statistics = employee.GetStatistics();
Console.WriteLine($"This is Max Value: {statistics.Max}");
Console.WriteLine($"This is Min Value: {statistics.Min}");
Console.WriteLine($"This is Average Value: {statistics.Average:N2}");